name: Bump package version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Automated Version Bump
        uses: '@lagoni/gh-action-dotnet-bump@master'
        with:
          commit-message: 'Bumped version to {{version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.OozeToken }}
