name: Create package

on:
  pull_request:
    branches: [ typed ]
    types: [ closed ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create package
      run: |
        cd ./src/Ooze.Typed
        dotnet pack -c Release -o pkg
    - name: Push package to GitHub registry
      run: dotnet nuget push ./src/Ooze.Typed/pkg/*.nupkg -k ${OOZE_TOKEN} -s https://nuget.pkg.github.com/DenisPav/index.json --skip-duplicate --no-symbols 
      env:
        OOZE_TOKEN: ${{ secrets.OozeToken }}
