name: Create package

on:
  pull_request:
    branches: [typed]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test ./tests/Ooze.Typed.Tests/Ooze.Typed.Tests.csproj
      - name: Create packages
        run: |
          cd ./src/Ooze.Typed
          dotnet pack -c Release -o pkg
      # - name: Add nuget source
      #   run: dotnet nuget add source https://nuget.pkg.github.com/DenisPav/index.json -u DenisPav -p ${OOZE_TOKEN} --store-password-in-clear-text
      #   env:
      #     OOZE_TOKEN: ${{ secrets.OozeToken }}
      - name: Push package to Nuget registry
        run: dotnet nuget push ./src/Ooze.Typed/pkg/*.nupkg -k ${NUGET_KEY} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
